export const initColors = {
    // XD Colors Start Mudassir
    "primary": "#EB39A2",
    "secondary": "#01ACDB",
    "yellowish": "#FFD100",
    "greyish_black": "#272727",
    "lightBlack": "#212121",
    "card": "#047A9E",
    // "grey": "#7D7D7D",
    "white": "#FFFFFF",
    "input_background": "#EFEFEF",
    "screen_background": "#F6F5FA",
    "gradient_array": ["#FFFFFF00", "#FFFFFFB3"],
    "disabled_button": "#707070",
    // XD Colors End Mudassir
    "text": "#343434",
    "border": "#707070",
    "notification": "#7359BE",
    "backgroundColor": "#1D1D1D",
    "navBackgroundColor": "#343434",
    "blueColor": "#05b7ed",
    "redColor": "#FF5757",
    "darkBlueColor": "#047A9E",
    "placeholderColor": "#545454",
    "buttonTextColor": "white",
    "textColor": "white",
    "iconColor": "#047A9E",
    "iconActiveColor": "#05B7ED",
    "navTextColor": "#C1C1C1",
    "navActiveTextColor": "white",
    "pinBall": "#D3D3D3",
    "black": "#000",
    "lightGreyBorder": '#BBBBBB',
    "light_grey": "#F6F5FA",
    "oldFlame": "#F3B8B4",
    "drWhite": "#FAFAFA",
    "subTextGreyColor": '#464646',
    "light_primary_color": '#E2DCF1',
    "grey": "#6B6B6B",
    "ASH_TO_ASH": "#4D4D4D",
    "dull_primary": '#F0F4F9',
    "light_input_border": "#CACDD1",
    "green": 'green'
}

